### ISSUE TITLE
[Imker] IOException

### ISSUE THREAD

**Issue by Nudin** [MarcoFalke/wiki-java-tools#1]
When trying to download pictures from the Category Pictures of the Year (finalist) I get:

java.io.IOException: Server returned HTTP response code: 503 for URL: https://commons.wikimedia.org/w/api.php?format=xml&maxlag=3&action=query&prop=imageinfo&iiprop=url&titles=File%3AAgamaSinaita01+ST+10.jpg&iiurlwidth=-1&iiurlheight=-1
You may submit a bug report to the github issue tracker:
https://github.com/MarcoFalke/wiki-java-tools/issues/new

**Comment by MarcoFalke** [comment]
Thank you for leaving the message. Indeed, I should change the code to catch such exceptions and repeat the last step.

**Comment by MarcoFalke** [comment]
If you don't want to wait for my fix, you can also just fire up the tool with the same settings and the download should continue where it stopped.

**Comment by Nudin** [comment]
Thanks, great tool!

**Comment by MarcoFalke** [comment]
Fixed in release [v15.05.12-imker](https://github.com/MarcoFalke/wiki-java-tools/releases).
