### ISSUE TITLE
[Imker] How to use the Java CLI?

### ISSUE THREAD

**Issue by mhulse** [MarcoFalke/wiki-java-tools#10]
Not seeing any instructions on this. Just curious if anyone has instructions or tips? I'd like to use the command line over the GUI. 👍

**Comment by MarcoFalke** [comment]
I have updated the Help page: https://commons.wikimedia.org/wiki/Commons:Imker_(batch_download)#Quick_start

Let me know if there are still questions.

**Comment by MarcoFalke** [comment]
For example on windows, you start cmd.exe and type:

```cmd
java -jar Downloads\Imker_v16.09.09\imker-cli.jar

**Comment by mhulse** [comment]
> For example on windows, you start cmd.exe and type:

Oh my gosh. That was too easy!!!!! Hehehe! I can't believe I didn't just try to run it! 😆 

Thanks you @MarcoFalke, I really appreciate your help!!!! :octocat:
