### ISSUE TITLE
[yacbot] token deprecation

### ISSUE THREAD

**Issue by Steinsplitter** [MarcoFalke/wiki-java-tools#12]
WARNING: getPageInfo: watchtoken is deprecated and will be removed shortly.

**Comment by MarcoFalke** [comment]
Thanks for the report. I think the issue lies within Wiki.java (thus, upstream).

I will merge the upstream changes in the next days, hopefully.

**Comment by Steinsplitter** [comment]
in case you haven't seen: https://github.com/MarcoFalke/wiki-java-tools/pull/11 - first. Otheriwise merge conflicts :(

**Comment by MarcoFalke** [comment]
Please reopen if this is still an issue with the release that will come tonight.
