### ISSUE TITLE
[Imker] CLI not exiting when child process in node.js

### ISSUE THREAD

**Issue by mhulse** [MarcoFalke/wiki-java-tools#13]
I am using node.js to run the jar as a child process.

Nether close or exit fire.

Looking at:

https://github.com/MarcoFalke/wiki-java-tools/blob/18ecd9ab0f69d7e528cb442f081bbdcf3397390e/src/app/ImkerCLI.java#L164-L178

Is there a need to `System.exit(1)` at the end of download to send the proper exit code?

From what I can see, my script is not getting any exit code, so the Java CLI just stops without error or success and I have to CTRL+C (which kill my parent process which I would like to avoid).

I could be totally barking up the wrong tree here, but do you think there's a way to make sure the CLI returns an exit code?

**Comment by MarcoFalke** [comment]
Are you sure the cli is done and not stuck while checking the checksums? See https://github.com/MarcoFalke/wiki-java-tools/blob/18ecd9ab0f69d7e528cb442f081bbdcf3397390e/src/app/ImkerCLI.java#L71

**Comment by mhulse** [comment]
Hi Marco! Thank you so much for reply, I really appreciate the help!

> Are you sure the cli is done and not stuck while checking the checksums? See https://github.com/MarcoFalke/wiki-java-tools/blob/18ecd9ab0f69d7e528cb442f081bbdcf3397390e/src/app/ImkerCLI.java#L71

Ah, sorry, I missed that. I should have looked around the code more.

I am not at my home computer where I can test, but the child process would download completely without error and then verify those downloads without error. Basically the whole process completed like it would normally (not as a child process), except it does not exit at end (as a child process).

I'm basically using node to download more than one category, in sequence, synchronously, in one sitting. I basically have the code working, I just can't move on to the next call to Imker CLI as the first one never exits.

I have not ruled out a bug with Node's child process exec. I'll keep exploring my options and will report back here my findings.

Thanks again for your help!

**Comment by MarcoFalke** [comment]
Let me know when you make progress. Also, you could try to set a different exit code in the last line of main() to see if this changes behavior.

**Comment by mhulse** [comment]
> Let me know when you make progress. Also, you could try to set a different exit code in the last line of main() to see if this changes behavior.

Ok, so, downloaded Imker, added the `exit(0)`, built with Gradle and ran my node script.... No love. :(

I also tried setting up a shell script with `exit 0`, and still no love.

Looks like it's a node-specific thing. :(

Sorry for making all of this noise.

Thanks for you help @MarcoFalke, I greatly appreciate it!

**Comment by mhulse** [comment]
Just for the sake of posterity, the real issue ended up being this:

```bash
yes "" | java -jar .......
```

I was using the bash `yes` command to skip the prompts.

After a bit more reading, it turns out that `yes` command sends continuous stream of `y` in order to answer yes to every prompt. While this is great to bypass any of the Imker commands during execution, it never let the java part finish as it was sending yes, continuously.

My fix, at least for now, was to do this:

```bash
echo "" | java -jar .....
```

The above works great for the first prompt of the command.

Unfortunately, it will not work if I get any other prompts.

Maybe it would be cool to have an option in the CLI to run in `--silent` mode? The assumption would be that a user wants to download images without being questioned; if there are any errors, just skip the bad images and finish normally (maybe with a console message letting user know what was skipped)?

While I don't know the GUI portion of this code, and I barely scratched surface of the CLI, I would not mind doing a PR. I'd imagine adding a `--silent` option would be easy enough … I would use the value of that arg to conditionally silence the prompts.

Thoughts? No worries if you think it's a bad idea. 👍 😆
