### ISSUE TITLE
[yacbot] Use crfs token

### ISSUE THREAD

**Issue by Steinsplitter** [MarcoFalke/wiki-java-tools#17]
switch bot to use crfs (https://github.com/MarcoFalke/wiki-java-tools/blob/yacbot/src/wiki/Wiki.java#L1378) token.

{
    "batchcomplete": "",
    "warnings": {
        "info": {
            "*": "The intoken parameter has been deprecated."
        }
    }
}

**Comment by MarcoFalke** [comment]
Closing, I will pull upstream in case https://github.com/MER-C/wiki-java/pull/144 is merged
