### ISSUE TITLE
[Imker] Exception when creating files with forbidden characters in Windows

### ISSUE THREAD

**Issue by MarcoFalke** [MarcoFalke/wiki-java-tools#3]
E.g. downloading http://commons.wikimedia.org/wiki/File:Windows-forbidden-chars*%22%3F.png gives ```java.io.FileNotFoundException: C:\Users\marco\Downloads\temp\4\Windows-forbidden-chars*"?.png  (The filename, directory name, or volume label syntax is incorrect)```

**Comment by MarcoFalke** [comment]
Thank you for letting me know this issue is relevant!

What would you expect the downloader to do for such files?

**Comment by MarcoFalke** [comment]
It is now possible to replace such characters. Important to note that the issue is not fully solved, though.

**Comment by ikarth** [comment]
Would using URLEncoder be sufficient? http://stackoverflow.com/questions/1652483/convert-between-url-and-windows-filename-java

**Comment by MarcoFalke** [comment]
URLEncoder does not encode ```*``` but it's a good start.

Also, if you want the encoding to be reversible and collision free, you'd have to encode all files downloaded.

**Comment by MarcoFalke** [comment]
Recent version should ask you if you want to url encode file names. I don't think I can do any more than that.
