### ISSUE TITLE
Imker Exception for files with a ? in filename

### ISSUE THREAD

**Issue by ikarth** [MarcoFalke/wiki-java-tools#5]
Imker fails with a Java.io.FileNotFound exception when attempting to download the following file:

https://commons.wikimedia.org/wiki/File:Attributed_to_Andr%C3%A9s_Lagarto,_Mexican_-_Nun%27s_Shield_showing_the_Virgin_and_Child_with_Saints_John_the_Baptist_and_Catherine_of_Alexandria_(%3F)_-_Google_Art_Project.jpg

This is likely because of the presence of the (?) in the image title, which is an invalid character for Windows filenames.

**Comment by ikarth** [comment]
Duplicate of #3

**Comment by MarcoFalke** [comment]
@ikarth It is now possible to replace such characters. You can test it in the latest version.
