### ISSUE TITLE
[Imker] Exception

### ISSUE THREAD

**Issue by Halibutt** [MarcoFalke/wiki-java-tools#6]
Sadly, the tool breaks when encountering quotation marks in a file name. How to reproduce? Try to download WLE 2014 files:
- https://commons.wikimedia.org/wiki/Category:WLE_finalist
- https://commons.wikimedia.org/wiki/Commons:Wiki_Loves_Earth_2014/Winners

Both downloading from the page and from the category break, most likely after encountering https://commons.wikimedia.org/wiki/File:%22A%C4%9F_qaya%22_%C5%9F%C9%99lal%C9%99si.JPG.

**Comment by MarcoFalke** [comment]
You can not create files with ```*"?``` in their name. see #3.

**Comment by MarcoFalke** [comment]
@Halibutt It is now possible to replace such characters. You can test it in the latest version.
